name: pr

on: pull_request

permissions: read-all

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3
      - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5  # v4
        with:
          python-version: 3.7
      - name: pre-commit
        uses: pre-commit/action@646c83fcd040023954eafda54b4db0192ce70507  # v3

  mypy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3
      - uses: actions/setup-python@b55428b1882923874294fa556849718a1d7f2ca5  # v4
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          pip install --upgrade pip
          pip install -r requirements-dev.txt
      - name: Run Mypy
        run: |
          mypy detect_secrets
          mypy testing

  main:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python: ['3.7', '3.8', '3.9']
    steps:
    - uses: actions/checkout@2541b1294d2704b0964813337f33b291d3f8596b  # v3
    - uses: actions/setup-python@98f2ad02fd48d057ee3b4d4f66525b231c3e52b6  # v3
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        pip install --upgrade pip
        pip install -r requirements-dev.txt
    - name: Sets env var for release
      if: ${{ matrix.os == 'macos-latest' && matrix.python == '3.7' }}
      run: |
        # NO_PROXY is needed to call requests API within a forked process
        # when using macOS and python version 3.7
        echo "NO_PROXY='*'" >> $GITHUB_ENV
    - name: Run tests
      run: pytest --strict-markers tests
